runtime:
  checkpoint_path: ???
  test_csv_path: ???
  val_csv_path: null
  model_config_path: vap/conf/default_config.yaml

  batch_size: 20
  num_workers: 4
  device: auto

  split_test_by_domain: true
